name: Build Android APK with EAS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Expo CLI and EAS CLI
        run: |
          npm install -g expo-cli eas-cli

      - name: Verify Installation
        run: |
          expo --version
          eas --version

      - name: Configure EAS Project
        run: |
          # Create complete eas.json configuration
          echo '{
            "cli": {
              "appVersionSource": "remote"
            },
            "build": {
              "production": {
                "android": {
                  "buildType": "apk",
                  "gradleCommand": ":app:assembleRelease"
                }
              }
            }
          }' > eas.json

          # Link project to your Expo account
          eas init --non-interactive --force --id ChecklistApp

          # Verify configuration
          cat eas.json
          eas project:info
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK
        run: |
          eas build -p android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./build/android/*.apk
